---

- name: zabbix yum repository
  template:
    src: zabbix.repo.j2
    dest: /etc/yum.repos.d/zabbix.repo

- name: zabbix package install
  yum: name={{ item }}
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-web-japanese
    - zabbix-agent

- name: mysqld install
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mysql56-server
    - mysql56
    - MySQL-python

- name: mysql-server service start
  service:
    name: mysqld
    state: started
    enabled: yes

- name: check zabbix database
  shell: mysql -u root -e "show databases;" | grep zabbix
  register: result

- name: create zabbix database
  command: mysql -u root -e \
           "create database zabbix character set utf8 collate utf8_bin;" -e \
           "grant all privileges on zabbix.* to zabbix@localhost identified by '{{zabbix_password}}';"
  when: result.stdout != "zabbix"

- name: check zabbix tables
  shell: mysql -u root -e "show tables from zabbix;"
  register: result2

- name: add tables
  shell: mysql -u root zabbix < {{ item }}
  args:
    chdir: /usr/share/doc/zabbix-server-mysql-2.4.8/create/
  with_items:
    - schema.sql
    - images.sql
    - data.sql
  when: result2.rc == 1
