---

- name: zabbix yum repository
  template:
    src: zabbix.repo.j2
    dest: /etc/yum.repos.d/zabbix.repo

- name: zabbix package install
  yum: name={{ item }}
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-web-japanese
    - zabbix-agent

- name: mysqld install
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mysql56-server
    - mysql56
    - MySQL-python

- name: mysql-server service start
  service:
    name: mysqld
    state: started
    enabled: yes

- name: check zabbix database
  command: mysql -u root -e "show databases;" | grep zabbix
  register: result
- name: debug 1
  debug: var=result
- name: debug 2
  debug: var=result.stdout

- name: create zabbix database
  command: mysql -u root -e \
           "create database zabbix character set utf8 collate utf8_bin;"

- name: permission setting for zabbix
  command: mysql -u root -e \
           "grant all privileges on zabbix.* to zabbix@localhost identified by {{zabbix_password}};"
