---

 - name: zabbix yum repository
   template:
     src: zabbix.repo.j2
     dest: /etc/yum.repos.d/zabbix.repo

 - name: zabbix package install
   yum: name={{ item }}
   with_items:
     - zabbix-server-mysql
     - zabbix-web-mysql
     - zabbix-web-japanese
     - zabbix-agent

- name: mysql yum repository
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
    state: present

- name: mysqld install
  yum:
    name: "{{ item }}"
    enablerepo: mysql56-community
    disablerepo: mysql57-community
    state: present
  with_items:
    - mysql-community-server
    - mysql-community-client
    - mysql-community-common
    - mysql-community-libs
    - mysql-community-libs-compat
  
